import Head from "next/head";
import { useState } from "react";
import token from "../constantes";
import styles from "../styles/Home.module.css";

export default function Home() {
  /**
   http://localhost:3000/uploads/e9f0fc46-2183-43dc-849b-144e10b10141&windows.png
   */
  const [image, setImage] = useState({});
  async function sendImage(e) {
    const body = new FormData();
    body.append("image", image, image.name);
    console.log(body);
    console.log(image);

    const res = await fetch("http://localhost:3000/api/hello", {
      method: "POST",
      body,
    });
    const msg = await res.json();
    console.log(msg);
  }

  function imageDropped(e) {
    e.preventDefault();
    setDragging(false);
    const file = e.dataTransfer.files[0];
    console.log(file);
    setImage(file);
  }
  const [dragging, setDragging] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <section
          onDragLeave={(e) => {
            e.preventDefault();
            setDragging(false);
          }}
          onDragOver={(e) => {
            e.preventDefault();
            setDragging(true);
          }}
          onDrop={imageDropped}
          className={
            "grid place-items-center w-[200px] h-[200px] border-dashed border-4 " +
            (dragging ? "border-blue-600" : "border-black")
          }
        >
          {image && <p>{image.name}</p>}
        </section>
        <button
          className="bg-blue-500 text-white m-2 p-2 text-2xl rounded-sm hover:bg-blue-700"
          onClick={sendImage}
        >
          send image
        </button>
      </main>
    </div>
  );
}
